### ISSUE TITLE
Performance improvement of computational_unit propagation

### ISSUE THREAD

**Issue by jpy-luke** [lukefi/metsi#16]
Current solution of doing deep copies ForestStand is wasteful. A lot of never-changing data gets copied introducing both memory and execution time problems.

A new solution should be found. The solution would exhibit the following properties:
* Only the changes to the OperationPayload.computational_unit (a ForestStand and its ReferenceTrees, TreeStrata) get copied in the OperationPayload copying process. This behaves as a partial overlay of the computational unit
* The overlay becomes a new member of the OperationPayload, but it should remain ignorant of the actual contents
* The model class ForestStand needs to be able to absorb the overlay so that they create a copy of themselves with the overlaid property values
* OperationPayload.computational_unit gets only copied via another function, which will fixate the overlay into a new copy of the computational_unit

From here on I see two alternative approaches:

ONE:

Model classes need changed implementation so that they can serve their properties using an overlay as the primary source and falling back to the actual object values. They also need changed implementation so that setting a property actually sets it in the overlay. It might be fairly difficult to get right the addition and removal of ReferenceTrees via this way.

TWO:

Change the contract of the operation functions from OpTuple to OpTriple. The new member would be the overlay. Responsibility of overlay management becomes a responsibility of the operation instead of complexifying the model classes. Adding and removing trees would become simpler, with a conscious choice of doing the overlay fixating then, and modifying the data as needed.

**Comment by jpy-luke** [comment]
Also pinging @taplem for commentary on this. I think you might have a very different approach to offer for consideration.

**Comment by taplem** [comment]
I use a dataframe/[SoA](https://en.wikipedia.org/wiki/AoS_and_SoA) type data structure for the tree data, so instead of having a list of tree objects I store each column separately. So the memory layout looks something like:
```
 header               data
[ spe ] -------> [ array of u8 ]
[  f  ] -------> [ array of f64 ]
[  d  ] -------> [ array of f64 ]
[  h  ] -------> [ array of f64 ]
```
When a savepoint (roughly the same thing as a `deepcopy` of the state in metsi) is created, only the header is copied, ie. the data itself is not included in the savepoint. Each column adds a fixed 8 bytes (on a 64-bit machine) to the savepoint size, independent of the number of trees.

This of course means that you can't modify data if a savepoint is pointing to it. So when you want to modify such data you instead allocate a new "version" of the column. Eg. after natural processes your memory would look like:
```
[ spe ] -------> [ array of u8 ]
[  f  ] -----+   [ array of f64 ] (old version, unmodified)
[  d  ] ---+ |   [ array of f64 ] (old version, unmodified)
[  h  ] -+ | |   [ array of f64 ] (old version, unmodified)
         | | +-> [ array of f64 ]
         | +---> [ array of f64 ]
         +-----> [ array of f64 ]
```
The tradeoff is that even changing an invidual tree requires reallocating the entire columns. But you almost never want to modify an invidual tree: natural processes, thinnings, etc. all modify each tree.

You also get all the usual benefits of the SoA layout: good cache locality, no padding, ability to use SIMD operations, etc.

**Comment by jpy-luke** [comment]
Thank you. This gave me an idea for the overlay, which doesn't require us to downright explode the class structure into primitive lists. Also taking into account that you're right, we do usually modify all trees at once.

1) Initiate the overlay at start of simulation as one empty list for the stand, and a dataframe for listed objects (reference trees and tree strata).
2) Maintain runtime reference map from listed objects to their column index in the dataframe for their type.
3) Maintain runtime property reference maps to a column index in the dataframe for that object type, or to the plain list for ForestStand.
3) Create object property accessors such that they access their value from the overlay, or return the original value.
4) Create object property setters so that they set the value in the dataframe, reserving a row number if this property is not yet presented. Operations would have a choice of using these for individual properties of individual objects.
5) Create a method for setting new lists for a property to the dataframe. Operations could use this to set new lists of property values. Then we trust that the operation does not mess up the ordering of the objects. Adding or removing objects should be handled somehow adjacent to this process.

The dataframes would surely be faster to copy for branches than making the deepcopy of the ForestStand. Maybe the dataframe could become a pandas or numpy dataframe.

The overlay could be maintained on the OperationPayload and aggregated as a ForestStand property for the current situation, or made a first class property of the ForestStand and data model library to allow them to carry the feature to any usage.
